### ISSUE TITLE
[HELP] Question regarding a pull request form a fork

### ISSUE THREAD

**Issue by MariusAlbrecht** [schnensch0/ziro#4]
I really liked the theme but wanted a nord theme variation of it for my personal use. I then just forked the repo and tried to add my theme only via the `colors.ini`. This however didn't quite work as wanted by me so I also modified the `user.css` file.

For context I added some new rules but also changed variables in existing rules

I just wanted to ask if trying to do a PR is even worthwhile considering my changes to the css will probably mess with the other color-schemes going on. Adding the nord theme for people to use may be nice.

**Comment by schnensch0** [comment]
no sorry, i won't merge it. people can still use your fork though if they want to the nord theme

**Comment by MariusAlbrecht** [comment]
yeah np! Just wanted to have asked
