### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by TarooqSalim** [schnensch0/ziro#5]
when i write in seaching box it shows me this
![Capture](https://user-images.githubusercontent.com/96233464/146346565-0064bf90-6050-4d65-9b2c-9d5b8b94c9e8.PNG)

**Comment by mxrixs** [comment]
what is the issue here? To me it seems like the text color is simply a bit light

**Comment by TarooqSalim** [comment]
i can't see what i'm writing because search box and text have the same color (white)
