### ISSUE TITLE
Color Scheme Spicetify [HELP]

### ISSUE THREAD

**Issue by Orions29** [schnensch0/ziro#6]
I'm sorry what is the color scheme i can't change the color

**Comment by MariusAlbrecht** [comment]
you can set the ziro theme by doing
`$ spicetify config current_ theme ziro`
and choose a specific colorway by doing
`$ spicetify config current_ theme <color theme>` (where you put one of blue-dark, blue-light, gray-dark, gray-light, green-dark, green-light, orange-dark, orange-light, purple-dark, purple-light, red-dark, red-light or a custom one you made isntead of <color theme>)
